# Generated by Django 6.0.7 on 2026-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('course_type', models.CharField(choices=[('theory', 'Theory Course (300 marks)'), ('sessional', 'Sessional Course (Custom Weights)')], default='theory', max_length=20)),
                ('credits', models.FloatField(default=3.0)),
                ('description', models.TextField(blank=True)),
                ('default_evaluations_json', models.TextField(default='[]', help_text='JSON list of default sessional evaluation components')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BUETian L2T2 Student', max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=20)),
                ('target_gpa', models.FloatField(default=3.75)),
                ('saved_state_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
